---
spring:
  datasource:
    username: osago
    password: uzb
    url: jdbc:oracle:thin:@osagodb-test.insuranceon.local:1521:OSAGO
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
  mail:
    host: smtp.gmail.com
    port: 587
    username: khayotovkhojiakbar@gmail.com
    password: qxzw xyxg gina awyv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.OracleLegacyDialect
token:
  expiration:
    time: 720
  security:
    key: nCIQjc9F+dH07C68ioqilIUTZp5VKQZKH4E9MP2yU5acglyVlCVGozPIZlhhENpk+X9NymDBLKRN51rqCTvp5A==
server:
  port: 8090
  url: http://localhost:8090
springdoc:
  api-docs:
    path: /v3/api-docs
